### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by F1R3L1GHT** [Focus04/Focus-Discord#3]
here is my entire error...

(node:3355) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at Object.execute (/Users/juantan/Downloads/focus/Commands/Info/help.js:29:75)
    at module.exports (/Users/juantan/Downloads/focus/Events/Messages/message.js:16:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:3355) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3355) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Focus04** [comment]
You seem to have a problem with the emojis displayed at the beginning of each command category. Please note that the emojis my bot uses are some of the custom emojis of my bot's support server. Your bot doesn't cache emojis it doesn't have access to (i.e emojis that don't share a mutual server with the bot, including my support server).

With that said, you can't get emojis from my server and attempt to have your bot use them, considering that your bot isn't part of my server.

None of those emojis are created by me and you can download them for personal use from certain websites, then replace my IDs with the ones on your server (or just remove emojis altogether).
