### ISSUE TITLE
what is the format for the .env file

### ISSUE THREAD

**Issue by CJFitchett2009** [Focus04/Focus-Discord#5]

**Comment by Focus04** [comment]
You'll have to include your bot token, API key for OpenWeatherMap, all the paths to your Mongo Atlas databases in it, and pretty much any information that you may consider _sensitive_. You can look around my code to see my environment variables' names and use them or use your own names.
`token` and `weatherid` are your bot's token and your weather API key respectively, rest of them are paths to your database.

**Comment by Focus04** [comment]
This might help you: [https://github.com/Focus04/Focus-Discord/issues/7](url)
